name: video_to_webp
description: "This project is a Flutter-based mobile app that converts video files to WebP animations."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.25+26
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  image_picker: ^1.1.2
  video_player: ^2.10.0
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7
  cloud_functions: ^5.5.2
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^18.0.1
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  gallery_saver_plus: ^3.2.8
  flutter_launcher_icons: ^0.14.4
  shared_preferences: ^2.5.3
  video_trimmer: ^5.0.0
  path_provider: ^2.1.4
  dio: ^5.4.0
  permission_handler: ^11.3.1
  media_scanner: ^2.2.0
  shorebird_code_push: ^2.0.4
  ffmpeg_kit_flutter_new: ^3.2.0
  google_mobile_ads: ^6.0.0
  in_app_update: ^4.2.5
  fluttertoast: ^8.2.8
  in_app_purchase: ^3.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - shorebird.yaml
flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/icon.png"
  adaptive_icon_background: "#5F8F3C"
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
